### User registration
POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "username": "test.webstorm",
  "email": "test.ws@email.com",
  "password": "password123"
}

### User login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "test.ws@email.com",
  "password": "password123"
}